### ISSUE TITLE
`-r` is said to be a shortcut for `--redirect`, but it isn't

### ISSUE THREAD

**Issue by skrattaren** [mgorny/pshs#1]
```
 % pshs -r cav@cel_2.mp4
pshs: invalid option -- 'r'
Usage: pshs [options] file [...]

Options:
    --help, -h           print this help message
    --version, -V        print program version and exit

    --no-upnp, -U        disable port redirection using UPnP
    --bind IP, -b IP     bind the server to IP address
    --port N, -p N       set port to listen on (default: random)
    --prefix PFX, -P PFX require all URLs to start with the prefix PFX
    --ssl, -s            serve files over HTTPS
    --no-upnp, -U        don't use UPNP to find the external IP address
    --redirect, -r       redirect / to a single provided file
```
`--redirect` does work, but it took me 5 minutes to realize that.

**Comment by mgorny** [comment]
I'm sorry about the issue. It seems that I've missed adding `r` to getopt() flag list.

**Comment by mgorny** [comment]
I see some potential issue with help message. Once I fix that, I will wrap up a bugfix release.

**Comment by skrattaren** [comment]
Thanks for hyperfast fix!
By the way, just out of curiosity: why `USE=ssl` is masked?  Not that I need it, but…

**Comment by mgorny** [comment]
Oh, i completely forgot about that one. It was because it needed new libevent which was masked at the time. It's fine now, so I'll drop the mask.
